//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class autenticacion
    {
        public long id { get; set; }
        public int id_usuario { get; set; }
        public string ip { get; set; }
        public string mac { get; set; }
        public System.DateTime fecha_inicio { get; set; }
        public string session { get; set; }
        public Nullable<System.DateTime> fecha_fin { get; set; }
    
        public virtual usuario usuario { get; set; }
    }
}
