//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class comentarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public comentarios()
        {
            this.reporte_comentarios = new HashSet<reporte_comentarios>();
        }
    
        public int id_comentario { get; set; }
        public string comentario { get; set; }
        public int id_post { get; set; }
        public Nullable<int> id_user { get; set; }
        public Nullable<int> estado { get; set; }
    
        public virtual estado_bloqueo estado_bloqueo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reporte_comentarios> reporte_comentarios { get; set; }
    }
}
