//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class controles
    {
        public int id { get; set; }
        public string nombre { get; set; }
        public int id_formulario { get; set; }
        public int id_idioma { get; set; }
        public string contenido { get; set; }
    
        public virtual formularios formularios { get; set; }
        public virtual idiomas idiomas { get; set; }
    }
}
