//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GamesColEntities : DbContext
    {
        public GamesColEntities()
            : base("name=GamesColEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<controles> controles { get; set; }
        public virtual DbSet<formularios> formularios { get; set; }
        public virtual DbSet<idiomas> idiomas { get; set; }
        public virtual DbSet<auditoria> auditoria { get; set; }
        public virtual DbSet<autenticacion> autenticacion { get; set; }
        public virtual DbSet<sesiones> sesiones { get; set; }
        public virtual DbSet<comentarios> comentarios { get; set; }
        public virtual DbSet<contato_usuarios> contato_usuarios { get; set; }
        public virtual DbSet<estado_bloqueo> estado_bloqueo { get; set; }
        public virtual DbSet<etiquetas> etiquetas { get; set; }
        public virtual DbSet<noticias> noticias { get; set; }
        public virtual DbSet<post> post { get; set; }
        public virtual DbSet<pqr> pqr { get; set; }
        public virtual DbSet<pqr_estados> pqr_estados { get; set; }
        public virtual DbSet<puntuacion> puntuacion { get; set; }
        public virtual DbSet<rango> rango { get; set; }
        public virtual DbSet<reporte_comentarios> reporte_comentarios { get; set; }
        public virtual DbSet<reporte_post> reporte_post { get; set; }
        public virtual DbSet<rol> rol { get; set; }
        public virtual DbSet<solicitud> solicitud { get; set; }
        public virtual DbSet<token_recuperacion_user> token_recuperacion_user { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
    }
}
