//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class pqr
    {
        public int id_pqr { get; set; }
        public int usuario { get; set; }
        public int solicitud { get; set; }
        public string contenido { get; set; }
        public string asunto { get; set; }
        public System.DateTime fecha { get; set; }
        public string respuesta { get; set; }
        public Nullable<int> id_contestador { get; set; }
        public Nullable<System.DateTime> fecha_respuesta { get; set; }
        public Nullable<int> estado_respuesta { get; set; }
    
        public virtual pqr_estados pqr_estados { get; set; }
        public virtual usuario usuario1 { get; set; }
    }
}
