//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class reporte_post
    {
        public int id_reporte { get; set; }
        public int id_post_reportador { get; set; }
        public string contenido_reporte { get; set; }
        public System.DateTime fecha_reporte { get; set; }
        public int user_reportador { get; set; }
        public Nullable<int> estado_resuelto { get; set; }
    
        public virtual post post { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
